version: '2'

networks:
    etcd-network:
        driver: bridge
services:
    etcd1:
        image: quay.io/coreos/etcd:latest
        restart: always
        ports:
            - 2379
            - 2380
        volumes:
          - ${ETCD_DATA}:/etcd1-data
        environment:
            ETCD_NAME: etcd1
            ETCD_DATA_DIR: /etcd1-data/etcd1.etcd 
            ETCDCTL_API: 3
            ETCD_INITIAL_ADVERTISE_PEER_URLS: https://etcd1:2380
            ETCD_INITIAL_CLUSTER: etcd1=https://etcd1:2380,etcd2=https://etcd2:2380,etcd3=https://etcd3:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_CLIENT_CERT_AUTH: 'true'
            ETCD_TRUSTED_CA_FILE: /etcd1-data/server.crt
            ETCD_CERT_FILE: /etcd1-data/server.crt
            ETCD_KEY_FILE: /etcd1-data/server.key
            ETCD_PEER_CLIENT_CERT_AUTH: 'true'
            ETCD_PEER_TRUSTED_CA_FILE: /etcd1-data/server.crt
            ETCD_PEER_CERT_FILE: /etcd1-data/server.crt
            ETCD_PEER_KEY_FILE: /etcd1-data/server.key
            ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: https://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: https://etcd1:2379
        networks:
          - etcd-network
    etcd2:
        image: quay.io/coreos/etcd:latest
        restart: always
        ports:
            - 2379
            - 2380
        volumes:
          - ${ETCD_DATA}:/etcd2-data
        environment:
            ETCD_NAME: etcd2
            ETCD_DATA_DIR: /etcd2-data/etcd2.etcd 
            ETCDCTL_API: 3
            ETCD_INITIAL_ADVERTISE_PEER_URLS: https://etcd2:2380
            ETCD_INITIAL_CLUSTER: etcd1=https://etcd1:2380,etcd2=https://etcd2:2380,etcd3=https://etcd3:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_CLIENT_CERT_AUTH: 'true'
            ETCD_TRUSTED_CA_FILE: /etcd2-data/server.crt
            ETCD_CERT_FILE: /etcd2-data/server.crt
            ETCD_KEY_FILE: /etcd2-data/server.key
            ETCD_PEER_CLIENT_CERT_AUTH: 'true'
            ETCD_PEER_TRUSTED_CA_FILE: /etcd2-data/server.crt
            ETCD_PEER_CERT_FILE: /etcd2-data/server.crt
            ETCD_PEER_KEY_FILE: /etcd2-data/server.key
            ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: https://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: https://etcd2:2379
        networks:
          - etcd-network
    etcd3:
        image: quay.io/coreos/etcd:latest
        restart: always
        ports:
            - 2379
            - 2380
        volumes:
          - ${ETCD_DATA}:/etcd3-data
        environment:
            ETCD_NAME: etcd3
            ETCD_DATA_DIR: /etcd3-data/etcd3.etcd
            ETCDCTL_API: 3
            ETCD_INITIAL_ADVERTISE_PEER_URLS: https://etcd3:2380
            ETCD_INITIAL_CLUSTER: etcd1=https://etcd1:2380,etcd2=https://etcd2:2380,etcd3=https://etcd3:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_CLIENT_CERT_AUTH: 'true'
            ETCD_TRUSTED_CA_FILE: /etcd3-data/server.crt
            ETCD_CERT_FILE: /etcd3-data/server.crt
            ETCD_KEY_FILE: /etcd3-data/server.key
            ETCD_PEER_CLIENT_CERT_AUTH: 'true'
            ETCD_PEER_TRUSTED_CA_FILE: /etcd3-data/server.crt
            ETCD_PEER_CERT_FILE: /etcd3-data/server.crt
            ETCD_PEER_KEY_FILE: /etcd3-data/server.key
            ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: https://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: https://etcd3:2379
        networks:
          - etcd-network










